FORMAT: 1A
HOST: http://swecune.com

#SWEcune

SWEcune provides a consumable API to view detailed information about Pokemon and related information such as moves and types.

##Pokemon [/pokemon]

## List all Pokemon [GET]

+ Response 200 (appolication/json)

        [
            {
                "id": 1,
                "name": "bulbasaur",
                "stats": [
                    {
                        "base_stat": 45,
                        "name": "speed"
                    },
                    {
                        "base_stat": 65,
                        "name": "special-defense"
                    },
                    {
                        "base_stat": 65,
                        "name": "special-attack"
                    },
                    {
                        "base_stat": 49,
                        "name": "defense"
                    },
                    {
                        "base_stat": 49,
                        "name": "attack"
                    },
                    {
                        "base_stat": 45,
                        "name": "hp"
                    }
                ],
                "primary_types": 12,
                "secondary_types": 4,
                "average_stats": 3,
                "move": [
                    {
                        "name": "vine-whip",
                        "id": 22
                    },
                    {
                        "name": "headbutt",
                        "id": 29
                    },
                ]
            },
            {
                "id": 2,
                "name": "ivysaur",
                "stats": [
                    {
                        "base_stat": 60,
                        "name": "speed"
                    },
                    {
                        "base_stat": 80,
                        "name": "special-defense"
                    },
                    {
                        "base_stat": 80,
                        "name": "special-attack"
                    },
                    {
                        "base_stat": 63,
                        "name": "defense"
                    },
                    {
                        "base_stat": 62,
                        "name": "attack"
                    },
                    {
                        "base_stat": 60,
                        "name": "hp"
                    }
                ],
                "primary_types": 12,
                "secondary_types": 4,
                "average_stats": 2,
                "move": [
                    {
                        "name": "swords-dance",
                        "id": 14
                    },
                    {
                        "name": "cut",
                        "id": 15
                    }
                ]
            }
        ]

## One Pokemon [/pokemon/{pokemon_id}]

+ Parameters
    + pokemon_id (number) - ID of the Pokemon in the form of an integer

### Information on one Pokemon [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "bulbasaur",
            "stats": [
                {
                    "base_stat": 45,
                    "name": "speed"
                },
                {
                    "base_stat": 65,
                    "name": "special-defense"
                },
                {
                    "base_stat": 65,
                    "name": "special-attack"
                },
                {
                    "base_stat": 49,
                    "name": "defense"
                },
                {
                    "base_stat": 49,
                    "name": "attack"
                },
                {
                    "base_stat": 45,
                    "name": "hp"
                }
            ],
            "primary_types": 12,
            "secondary_types": 4,
            "average_stats": 3,
            "move": [
                {
                    "name": "vine-whip",
                    "id": 22
                },
                {
                    "name": "headbutt",
                    "id": 29
                }
            ]
        }

## Move [/move]

### List all Moves [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "pound",
                "accuracy": 100,
                "pp": 35,
                "priority": 0,
                "power": 40,
                "damage_class": "physical",
                "move_type": "normal"
            },
            {
                "id": 2,
                "name": "karate-chop",
                "accuracy": 100,
                "pp": 25,
                "priority": 0,
                "power": 50,
                "damage_class": "physical",
                "move_type": "fighting"
            }
        ]


## One Move [/move/{move_id}]

+ Parameters
    + move_id (number) - ID of the move in the form of an integer

### Information on one Pokemon [GET]

+ Response 200 (application/json)


        {
            "id": 1,
            "name": "pound",
            "accuracy": 100,
            "pp": 35,
            "priority": 0,
            "power": 40,
            "damage_class": "physical",
            "move_type": "normal"
        }


## Type [/type]

### List all types [GET]

+ Response 200(application/json)

        [
            {
                "id": 1,
                "name": "normal",
                "resistance": [
                    {
                        "id": 8
                    }
                ],
                "strength": [
                    {
                        "id": 6
                    },
                    {
                        "id": 9
                    }
                ],
                "immunity": []
                "generation": 1
            },
            {
                "id": 2,
                "name": "fighting",
                "resistance": [
                    {
                        "id": 8
                    }
                ],
                "strength": [
                    {
                        "id": 3
                    }
                ],
                "immunity": [
                    {
                        "id": 4
                    }
                ]
                "generation": 1
            }
        ]


## One type [/type/{type_id}]

+ Parameters
    + type_id (number) - ID of the type in the form of an integer

### Information on one type [GET]

+ Response 200(application/json)


        {
            "id": 1,
            "name": "normal",
            "resistance": [
                {
                    "id": 8
                }
            ],
            "strength": [
                {
                    "id": 6
                },
                {
                    "id": 9
                }
            ],
            "immunity": []
            "generation": 1
        }