FORMAT: 1A
HOST: http://swecune.com/api/v1

#SWEcune

SWEcune provides a consumable API to view detailed information about Pokemon and related information such as moves and types.

##Pokemon [/pokemon]

## List all Pokemon [GET]

+ Response 200 (application/json)
        [
            {
                "id": 1,
                "name": "bulbasaur",
                "primary_type": 12,
                "secondary_type": 4,
                "attack": 1,
                "defense": 1,
                "hp": 45,
                "speed": 1,
                "special_attack": 1,
                "special_defense": 1,
                "average_stats": 3,
                "moves": [
                    22,
                    29
                ],
            },
            {
                "id": 2,
                "name": "ivysaur",
                "primary_types": 12,
                "secondary_types": 4,
                "attack": 62,
                "defense": 63,
                "hp": 60,
                "speed": 60,
                "special_defense": 80,
                "special_attack": 80,
                "average_stats": 2,
                "move": [
                    14,
                    15
                ]
            }

        ] 

## One Pokemon [/pokemon/{pokemon_id}]

+ Parameters
    + pokemon_id (number) - ID of the Pokemon in the form of an integer

### Information on one Pokemon [GET]

+ Response 200 (application/json)
        {
            "id": 1,
            "name": "bulbasaur",
            "primary_type": 12,
            "secondary_type": 4,
            "attack": 1,
            "defense": 1,
            "hp": 45,
            "speed": 1,
            "special_attack": 1,
            "special_defense": 1,
            "average_stats": 3,
            "moves": [
                22,
                29
            ],
        }

## Move [/move]

### List all Moves [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "pound",
                "accuracy": 100,
                "pp": 35,
                "priority": 0,
                "power": 40,
                "damage_class": "physical",
                "move_type": "normal"
                "pokemon" : [
                    1,
                    2
                ],
                "move": [
                    1,
                    3
                ]
            },
            {
                "id": 2,
                "name": "karate-chop",
                "accuracy": 100,
                "pp": 25,
                "priority": 0,
                "power": 50,
                "damage_class": "physical",
                "move_type": "fighting"
                "pokemon" : [
                    1,
                    2
                ],
                "move": [
                    1,
                    3
                ]
            }
        ]


## One Move [/move/{move_id}]

+ Parameters
    + move_id (number) - ID of the move in the form of an integer

### Information on one Move [GET]

+ Response 200 (application/json)


        {
            "id": 1,
            "name": "pound",
            "accuracy": 100,
            "pp": 35,
            "priority": 0,
            "power": 40,
            "damage_class": "physical",
            "move_type": "normal"
            "pokemon" : [
                1,
                2
            ]
        }


## Type [/type]

### List all types [GET]

+ Response 200(application/json)

        [
            {
                "id": 1,
                "name": "normal",
                "resistance": [
                    8
                ],
                "strength": [
                    6,
                    9
                ],
                "immunity": []
                "generation": 1
                "pokemon" : [
                    1,
                    2
                ]
            },
            {
                "id": 2,
                "name": "fighting",
                "resistance": [
                    8
                ],
                "strength": [
                    3
                ],
                "immunity": [
                    4
                ]
                "generation": 1
                "pokemon" : [
                    1,
                    2
                ]
            }
        ]


## One type [/type/{type_id}]

+ Parameters
    + type_id (number) - ID of the type in the form of an integer

### Information on one type [GET]

+ Response 200(application/json)


        {
            "id": 1,
            "name": "normal",
            "resistance": [
                8
            ],
            "strength": [
                6,
                9
            ],
            "immunity": []
            "generation": 1
            "pokemon" : [
                1,
                2
            ]
            "move": [
                1,
                3
            ]
        }