FORMAT: 1A
HOST: http://swecune.com/api/

#SWEcune

SWEcune provides a consumable API to view detailed information about Pokemon and related information such as moves and types.

##Pokemon [/pokemon/{?offset,limit}]

+ Parameters
    + offset (integer, optional) - ID of the first Pokemon to be returned
        + Default: 1
    + limit (integer, optional) - Number of Pokemon to return
        + Default: 10

## List all Pokemon [GET]

+ Response 200 (application/json)

        [
            {
                "id":1,
                "name":"Bulbasaur",
                "stats":[
                    {
                        "name":"speed",
                        "base_stat":45
                    },
                    {
                        "name":"special_defense",
                        "base_stat":65
                    },
                    {
                        "name":"special_attack",
                        "base_stat":65
                    },
                    {
                        "name":"defense",
                        "base_stat":49
                    },
                    {
                        "name":"attack",
                        "base_stat":49
                    },
                    {
                        "name":"hp",
                        "base_stat":45
                    }
                ],
                "primary_type":12,
                "secondary_type":4,
                "average_stats":53,
                "moves":[
                    13,
                    14,
                    15,
                    20,
                    22,
                    29,
                    33,
                    34,
                    36,
                    38,
                    45,
                    70,
                    72,
                    73,
                    74,
                    75,
                    76,
                    77,
                    79,
                    80,
                    81,
                    92,
                    99,
                    102,
                    104,
                    111,
                    113,
                    115,
                    117,
                    124,
                    130,
                    133,
                    148,
                    156,
                    164,
                    173,
                    174,
                    182,
                    188,
                    189,
                    202,
                    203,
                    204,
                    207,
                    210,
                    213,
                    214,
                    216,
                    218,
                    219,
                    230,
                    235,
                    237,
                    241,
                    249,
                    263,
                    267,
                    275,
                    282,
                    290,
                    320,
                    331,
                    345,
                    363,
                    388,
                    402,
                    412,
                    437,
                    438,
                    445,
                    447,
                    474,
                    496,
                    497,
                    520,
                    580,
                    590
                ]
            },
            {
                "id":2,
                "name":"Ivysaur",
                "stats":[
                    {
                        "name":"speed",
                        "base_stat":60
                    },
                    {
                        "name":"special_defense",
                        "base_stat":80
                    },
                    {
                        "name":"special_attack",
                        "base_stat":80
                    },
                    {
                        "name":"defense",
                        "base_stat":63
                    },
                    {
                        "name":"attack",
                        "base_stat":62
                    },
                    {
                        "name":"hp",
                        "base_stat":60
                    }
                ],
                "primary_type":12,
                "secondary_type":4,
                "average_stats":67,
                "moves":[
                    14,
                    15,
                    20,
                    22,
                    29,
                    33,
                    34,
                    36,
                    38,
                    45,
                    70,
                    72,
                    73,
                    74,
                    75,
                    76,
                    77,
                    79,
                    81,
                    92,
                    99,
                    102,
                    104,
                    111,
                    113,
                    115,
                    117,
                    148,
                    156,
                    164,
                    173,
                    174,
                    182,
                    188,
                    189,
                    202,
                    203,
                    207,
                    210,
                    213,
                    214,
                    216,
                    218,
                    219,
                    230,
                    235,
                    237,
                    241,
                    249,
                    263,
                    267,
                    282,
                    290,
                    331,
                    363,
                    388,
                    402,
                    412,
                    445,
                    447,
                    474,
                    496,
                    497,
                    520,
                    590
                ]
            },
            {
                "id":3,
                "name":"Venusaur",
                "stats":[
                    {
                        "name":"speed",
                        "base_stat":80
                    },
                    {
                        "name":"special_defense",
                        "base_stat":100
                    },
                    {
                        "name":"special_attack",
                        "base_stat":100
                    },
                    {
                        "name":"defense",
                        "base_stat":83
                    },
                    {
                        "name":"attack",
                        "base_stat":82
                    },
                    {
                        "name":"hp",
                        "base_stat":80
                    }
                ],
                "primary_type":12,
                "secondary_type":4,
                "average_stats":87,
                "moves":[
                    14,
                    15,
                    20,
                    22,
                    29,
                    33,
                    34,
                    36,
                    38,
                    45,
                    46,
                    63,
                    70,
                    72,
                    73,
                    74,
                    75,
                    76,
                    77,
                    79,
                    80,
                    81,
                    89,
                    92,
                    99,
                    102,
                    104,
                    111,
                    113,
                    115,
                    117,
                    148,
                    156,
                    164,
                    173,
                    174,
                    182,
                    188,
                    189,
                    200,
                    202,
                    203,
                    207,
                    210,
                    213,
                    214,
                    216,
                    218,
                    219,
                    230,
                    235,
                    237,
                    241,
                    249,
                    263,
                    267,
                    282,
                    290,
                    331,
                    335,
                    338,
                    363,
                    388,
                    402,
                    412,
                    416,
                    431,
                    445,
                    447,
                    474,
                    496,
                    497,
                    520,
                    523,
                    572,
                    590
                ]
            },
            {
                "id":4,
                "name":"Charmander",
                "stats":[
                    {
                        "name":"speed",
                        "base_stat":65
                    },
                    {
                        "name":"special_defense",
                        "base_stat":50
                    },
                    {
                        "name":"special_attack",
                        "base_stat":60
                    },
                    {
                        "name":"defense",
                        "base_stat":43
                    },
                    {
                        "name":"attack",
                        "base_stat":52
                    },
                    {
                        "name":"hp",
                        "base_stat":39
                    }
                ],
                "primary_type":10,
                "secondary_type":null,
                "average_stats":51,
                "moves":[
                    5,
                    7,
                    9,
                    10,
                    14,
                    15,
                    25,
                    29,
                    34,
                    36,
                    38,
                    43,
                    44,
                    45,
                    52,
                    53,
                    66,
                    68,
                    69,
                    70,
                    82,
                    83,
                    91,
                    92,
                    99,
                    102,
                    104,
                    108,
                    111,
                    115,
                    117,
                    126,
                    129,
                    130,
                    156,
                    157,
                    163,
                    164,
                    173,
                    174,
                    182,
                    184,
                    187,
                    189,
                    200,
                    203,
                    207,
                    210,
                    213,
                    214,
                    216,
                    218,
                    223,
                    225,
                    231,
                    232,
                    237,
                    241,
                    242,
                    246,
                    249,
                    251,
                    257,
                    261,
                    263,
                    264,
                    280,
                    290,
                    314,
                    315,
                    317,
                    332,
                    337,
                    349,
                    363,
                    374,
                    394,
                    406,
                    407,
                    421,
                    424,
                    445,
                    468,
                    481,
                    488,
                    496,
                    497,
                    510,
                    517,
                    519,
                    590,
                    612
                ]
            },
            {
                "id":5,
                "name":"Charmeleon",
                "stats":[
                    {
                        "name":"speed",
                        "base_stat":80
                    },
                    {
                        "name":"special_defense",
                        "base_stat":65
                    },
                    {
                        "name":"special_attack",
                        "base_stat":80
                    },
                    {
                        "name":"defense",
                        "base_stat":58
                    },
                    {
                        "name":"attack",
                        "base_stat":64
                    },
                    {
                        "name":"hp",
                        "base_stat":58
                    }
                ],
                "primary_type":10,
                "secondary_type":null,
                "average_stats":67,
                "moves":[
                    5,
                    7,
                    9,
                    10,
                    14,
                    15,
                    25,
                    29,
                    34,
                    36,
                    38,
                    43,
                    45,
                    52,
                    53,
                    66,
                    68,
                    69,
                    70,
                    82,
                    83,
                    91,
                    92,
                    99,
                    102,
                    104,
                    108,
                    111,
                    115,
                    117,
                    126,
                    129,
                    130,
                    156,
                    157,
                    163,
                    164,
                    173,
                    174,
                    182,
                    184,
                    189,
                    200,
                    203,
                    207,
                    210,
                    213,
                    214,
                    216,
                    218,
                    223,
                    225,
                    231,
                    232,
                    237,
                    241,
                    249,
                    257,
                    261,
                    263,
                    264,
                    280,
                    290,
                    315,
                    317,
                    332,
                    337,
                    363,
                    374,
                    406,
                    421,
                    424,
                    445,
                    468,
                    481,
                    488,
                    496,
                    497,
                    510,
                    517,
                    519,
                    590,
                    612
                ]
            },
            {
                "id":6,
                "name":"Charizard",
                "stats":[
                    {
                        "name":"speed",
                        "base_stat":100
                    },
                    {
                        "name":"special_defense",
                        "base_stat":85
                    },
                    {
                        "name":"special_attack",
                        "base_stat":109
                    },
                    {
                        "name":"defense",
                        "base_stat":78
                    },
                    {
                        "name":"attack",
                        "base_stat":84
                    },
                    {
                        "name":"hp",
                        "base_stat":78
                    }
                ],
                "primary_type":10,
                "secondary_type":3,
                "average_stats":89,
                "moves":[
                    5,
                    7,
                    9,
                    10,
                    14,
                    15,
                    17,
                    19,
                    25,
                    29,
                    34,
                    36,
                    38,
                    43,
                    45,
                    46,
                    52,
                    53,
                    63,
                    66,
                    68,
                    69,
                    70,
                    76,
                    82,
                    83,
                    89,
                    90,
                    91,
                    92,
                    99,
                    102,
                    104,
                    108,
                    111,
                    115,
                    117,
                    126,
                    129,
                    130,
                    156,
                    157,
                    163,
                    164,
                    173,
                    174,
                    182,
                    184,
                    189,
                    200,
                    201,
                    203,
                    207,
                    210,
                    211,
                    213,
                    214,
                    216,
                    218,
                    223,
                    225,
                    231,
                    232,
                    237,
                    239,
                    241,
                    249,
                    257,
                    261,
                    263,
                    264,
                    280,
                    290,
                    307,
                    314,
                    315,
                    317,
                    332,
                    337,
                    355,
                    363,
                    366,
                    374,
                    394,
                    403,
                    406,
                    411,
                    416,
                    421,
                    424,
                    432,
                    445,
                    466,
                    468,
                    481,
                    488,
                    496,
                    497,
                    507,
                    510,
                    517,
                    519,
                    523,
                    525,
                    590,
                    612
                ]
            },
            {
                "id":7,
                "name":"Squirtle",
                "stats":[
                    {
                        "name":"speed",
                        "base_stat":43
                    },
                    {
                        "name":"special_defense",
                        "base_stat":64
                    },
                    {
                        "name":"special_attack",
                        "base_stat":50
                    },
                    {
                        "name":"defense",
                        "base_stat":65
                    },
                    {
                        "name":"attack",
                        "base_stat":48
                    },
                    {
                        "name":"hp",
                        "base_stat":44
                    }
                ],
                "primary_type":11,
                "secondary_type":null,
                "average_stats":52,
                "moves":[
                    5,
                    8,
                    25,
                    29,
                    33,
                    34,
                    36,
                    38,
                    39,
                    44,
                    54,
                    55,
                    56,
                    57,
                    58,
                    59,
                    61,
                    66,
                    68,
                    69,
                    70,
                    91,
                    92,
                    93,
                    99,
                    102,
                    104,
                    110,
                    111,
                    114,
                    115,
                    117,
                    127,
                    130,
                    145,
                    156,
                    164,
                    173,
                    174,
                    175,
                    182,
                    189,
                    193,
                    196,
                    203,
                    205,
                    207,
                    213,
                    214,
                    216,
                    218,
                    223,
                    229,
                    231,
                    237,
                    240,
                    243,
                    249,
                    250,
                    252,
                    258,
                    263,
                    264,
                    280,
                    281,
                    287,
                    290,
                    291,
                    300,
                    317,
                    323,
                    330,
                    334,
                    352,
                    360,
                    362,
                    363,
                    374,
                    392,
                    396,
                    401,
                    406,
                    428,
                    445,
                    453,
                    496,
                    503,
                    518,
                    590,
                    612
                ]
            },
            {
                "id":8,
                "name":"Wartortle",
                "stats":[
                    {
                        "name":"speed",
                        "base_stat":58
                    },
                    {
                        "name":"special_defense",
                        "base_stat":80
                    },
                    {
                        "name":"special_attack",
                        "base_stat":65
                    },
                    {
                        "name":"defense",
                        "base_stat":80
                    },
                    {
                        "name":"attack",
                        "base_stat":63
                    },
                    {
                        "name":"hp",
                        "base_stat":59
                    }
                ],
                "primary_type":11,
                "secondary_type":null,
                "average_stats":67,
                "moves":[
                    5,
                    8,
                    25,
                    29,
                    33,
                    34,
                    36,
                    38,
                    39,
                    44,
                    55,
                    56,
                    57,
                    58,
                    59,
                    61,
                    66,
                    68,
                    69,
                    70,
                    91,
                    92,
                    99,
                    102,
                    104,
                    110,
                    111,
                    115,
                    117,
                    127,
                    130,
                    145,
                    156,
                    164,
                    173,
                    174,
                    182,
                    189,
                    196,
                    203,
                    205,
                    207,
                    213,
                    214,
                    216,
                    218,
                    223,
                    229,
                    231,
                    237,
                    240,
                    249,
                    250,
                    258,
                    263,
                    264,
                    280,
                    290,
                    291,
                    317,
                    334,
                    352,
                    360,
                    362,
                    363,
                    374,
                    401,
                    406,
                    428,
                    445,
                    496,
                    503,
                    518,
                    590,
                    612
                ]
            },
            {
                "id":9,
                "name":"Blastoise",
                "stats":[
                    {
                        "name":"speed",
                        "base_stat":78
                    },
                    {
                        "name":"special_defense",
                        "base_stat":105
                    },
                    {
                        "name":"special_attack",
                        "base_stat":85
                    },
                    {
                        "name":"defense",
                        "base_stat":100
                    },
                    {
                        "name":"attack",
                        "base_stat":83
                    },
                    {
                        "name":"hp",
                        "base_stat":79
                    }
                ],
                "primary_type":11,
                "secondary_type":null,
                "average_stats":88,
                "moves":[
                    5,
                    8,
                    25,
                    29,
                    33,
                    34,
                    36,
                    38,
                    39,
                    44,
                    46,
                    55,
                    56,
                    57,
                    58,
                    59,
                    61,
                    63,
                    66,
                    68,
                    69,
                    70,
                    89,
                    90,
                    91,
                    92,
                    99,
                    102,
                    104,
                    110,
                    111,
                    115,
                    117,
                    127,
                    130,
                    145,
                    156,
                    157,
                    164,
                    173,
                    174,
                    182,
                    189,
                    196,
                    200,
                    203,
                    205,
                    207,
                    213,
                    214,
                    216,
                    218,
                    223,
                    229,
                    231,
                    237,
                    240,
                    249,
                    250,
                    258,
                    263,
                    264,
                    280,
                    290,
                    291,
                    308,
                    317,
                    324,
                    334,
                    352,
                    360,
                    362,
                    363,
                    374,
                    399,
                    401,
                    406,
                    411,
                    416,
                    419,
                    428,
                    430,
                    431,
                    445,
                    479,
                    496,
                    503,
                    518,
                    523,
                    525,
                    590,
                    612
                ]
            },
            {
                "id":10,
                "name":"Caterpie",
                "stats":[
                    {
                        "name":"speed",
                        "base_stat":45
                    },
                    {
                        "name":"special_defense",
                        "base_stat":20
                    },
                    {
                        "name":"special_attack",
                        "base_stat":20
                    },
                    {
                        "name":"defense",
                        "base_stat":35
                    },
                    {
                        "name":"attack",
                        "base_stat":30
                    },
                    {
                        "name":"hp",
                        "base_stat":45
                    }
                ],
                "primary_type":7,
                "secondary_type":null,
                "average_stats":32,
                "moves":[
                    33,
                    81,
                    173,
                    450,
                    527
                ]
            }
        ]

### Information on one Pokemon [GET /pokemon/{pokemon_id}]

+ Parameters
    + pokemon_id (number) - ID of the Pokemon in the form of an integer

+ Response 200 (application/json)

        {
            "id":1,
            "name":"Bulbasaur",
            "stats":[
                {
                    "name":"speed",
                    "base_stat":45
                },
                {
                    "name":"special_defense",
                    "base_stat":65
                },
                {
                    "name":"special_attack",
                    "base_stat":65
                },
                {
                    "name":"defense",
                    "base_stat":49
                },
                {
                    "name":"attack",
                    "base_stat":49
                },
                {
                    "name":"hp",
                    "base_stat":45
                }
            ],
            "primary_type":12,
            "secondary_type":4,
            "average_stats":53,
            "moves":[
                13,
                14,
                15,
                20,
                22,
                29,
                33,
                34,
                36,
                38,
                45,
                70,
                72,
                73,
                74,
                75,
                76,
                77,
                79,
                80,
                81,
                92,
                99,
                102,
                104,
                111,
                113,
                115,
                117,
                124,
                130,
                133,
                148,
                156,
                164,
                173,
                174,
                182,
                188,
                189,
                202,
                203,
                204,
                207,
                210,
                213,
                214,
                216,
                218,
                219,
                230,
                235,
                237,
                241,
                249,
                263,
                267,
                275,
                282,
                290,
                320,
                331,
                345,
                363,
                388,
                402,
                412,
                437,
                438,
                445,
                447,
                474,
                496,
                497,
                520,
                580,
                590
            ]
        }

## Move [/move/{?offset,limit}]

### List all Moves [GET]

+ Parameters
    + offset (integer, optional) - ID of the first Move to be returned
        + Default: 1
    + limit (integer, optional) - Number of Move to return
        + Default: 10

+ Response 200 (application/json)

        [
            {
                "id":1,
                "name":"Pound",
                "accuracy":100,
                "pp":35,
                "priority":0,
                "power":40,
                "damage_class":"physical",
                "move_type":1,
                "pokemon":[
                    174,
                    173,
                    242,
                    254,
                    10065,
                    252,
                    253,
                    275,
                    274,
                    238,
                    10069,
                    657,
                    656,
                    440,
                    124,
                    97,
                    96,
                    192,
                    393,
                    457,
                    428,
                    316,
                    576,
                    574,
                    427,
                    572,
                    456,
                    575,
                    594,
                    89,
                    295,
                    113,
                    317,
                    293,
                    151,
                    294,
                    531,
                    694,
                    534,
                    35,
                    532,
                    533,
                    39,
                    88,
                    10088,
                    619,
                    622,
                    623,
                    569,
                    658,
                    620,
                    568
                ]
            },
            {
                "id":3,
                "name":"Double-Slap",
                "accuracy":85,
                "pp":10,
                "priority":0,
                "power":15,
                "damage_class":"physical",
                "move_type":1,
                "pokemon":[
                    242,
                    172,
                    10069,
                    40,
                    36,
                    60,
                    62,
                    122,
                    186,
                    124,
                    190,
                    439,
                    576,
                    574,
                    418,
                    572,
                    575,
                    594,
                    300,
                    301,
                    113,
                    531,
                    35,
                    39,
                    61,
                    619,
                    569,
                    620,
                    659,
                    568
                ]
            },
            {
                "id":4,
                "name":"Comet-Punch",
                "accuracy":85,
                "pp":15,
                "priority":0,
                "power":18,
                "damage_class":"physical",
                "move_type":1,
                "pokemon":[
                    674,
                    107,
                    115,
                    10039,
                    532,
                    165,
                    166,
                    675
                ]
            },
            {
                "id":5,
                "name":"Mega-Punch",
                "accuracy":85,
                "pp":20,
                "priority":0,
                "power":80,
                "damage_class":"physical",
                "move_type":1,
                "pokemon":[
                    241,
                    240,
                    174,
                    255,
                    173,
                    259,
                    242,
                    176,
                    254,
                    181,
                    239,
                    210,
                    252,
                    216,
                    297,
                    257,
                    248,
                    172,
                    253,
                    217,
                    209,
                    238,
                    175,
                    272,
                    56,
                    40,
                    36,
                    62,
                    122,
                    183,
                    312,
                    314,
                    195,
                    186,
                    124,
                    184,
                    199,
                    97,
                    225,
                    352,
                    96,
                    10003,
                    105,
                    104,
                    356,
                    190,
                    25,
                    75,
                    106,
                    313,
                    185,
                    10001,
                    150,
                    107,
                    108,
                    8,
                    57,
                    143,
                    6,
                    94,
                    295,
                    296,
                    68,
                    302,
                    260,
                    307,
                    308,
                    67,
                    80,
                    303,
                    311,
                    113,
                    115,
                    74,
                    64,
                    256,
                    112,
                    306,
                    63,
                    157,
                    293,
                    126,
                    151,
                    76,
                    294,
                    55,
                    66,
                    289,
                    160,
                    287,
                    10039,
                    331,
                    327,
                    332,
                    35,
                    326,
                    65,
                    39,
                    486,
                    158,
                    10002,
                    7,
                    377,
                    288,
                    180,
                    5,
                    165,
                    335,
                    61,
                    9,
                    286,
                    4,
                    166,
                    159,
                    31,
                    125,
                    383,
                    622,
                    623,
                    54,
                    34,
                    379,
                    26,
                    378
                ]
            },
            {
                "id":6,
                "name":"Pay-Day",
                "accuracy":100,
                "pp":20,
                "priority":0,
                "power":40,
                "damage_class":"physical",
                "move_type":1,
                "pokemon":[
                    56,
                    79,
                    52,
                    187,
                    25,
                    150,
                    57,
                    143,
                    509,
                    80,
                    112,
                    151,
                    55,
                    87,
                    86,
                    53,
                    31,
                    54,
                    34,
                    26
                ]
            },
            {
                "id":10,
                "name":"Scratch",
                "accuracy":100,
                "pp":35,
                "priority":0,
                "power":40,
                "damage_class":"physical",
                "move_type":1,
                "pokemon":[
                    255,
                    215,
                    291,
                    216,
                    257,
                    10050,
                    217,
                    56,
                    689,
                    28,
                    50,
                    677,
                    52,
                    46,
                    678,
                    352,
                    190,
                    10057,
                    424,
                    435,
                    434,
                    359,
                    57,
                    392,
                    391,
                    10034,
                    10066,
                    510,
                    10035,
                    6,
                    141,
                    509,
                    140,
                    513,
                    511,
                    47,
                    302,
                    432,
                    292,
                    256,
                    431,
                    27,
                    461,
                    55,
                    655,
                    289,
                    160,
                    287,
                    529,
                    51,
                    347,
                    530,
                    161,
                    158,
                    53,
                    162,
                    288,
                    5,
                    335,
                    29,
                    4,
                    159,
                    31,
                    654,
                    290,
                    10025,
                    515,
                    571,
                    653,
                    390,
                    30,
                    611,
                    688,
                    570,
                    610,
                    624,
                    54,
                    348,
                    612,
                    621,
                    625
                ]
            },
            {
                "id":11,
                "name":"Vice-Grip",
                "accuracy":100,
                "pp":30,
                "priority":0,
                "power":55,
                "damage_class":"physical",
                "move_type":1,
                "pokemon":[
                    10040,
                    693,
                    632,
                    342,
                    601,
                    599,
                    98,
                    10052,
                    99,
                    303,
                    127,
                    692,
                    600,
                    341
                ]
            },
            {
                "id":12,
                "name":"Guillotine",
                "accuracy":30,
                "pp":5,
                "priority":0,
                "power":null,
                "damage_class":"physical",
                "move_type":1,
                "pokemon":[
                    10040,
                    632,
                    342,
                    207,
                    98,
                    99,
                    472,
                    127,
                    611,
                    610,
                    624,
                    612,
                    625,
                    341
                ]
            },
            {
                "id":13,
                "name":"Razor-Wind",
                "accuracy":100,
                "pp":10,
                "priority":0,
                "power":80,
                "damage_class":"special",
                "move_type":1,
                "pokemon":[
                    212,
                    273,
                    252,
                    274,
                    203,
                    662,
                    663,
                    357,
                    21,
                    16,
                    207,
                    149,
                    123,
                    10057,
                    359,
                    146,
                    10046,
                    18,
                    418,
                    142,
                    42,
                    519,
                    12,
                    520,
                    540,
                    141,
                    144,
                    419,
                    145,
                    83,
                    17,
                    151,
                    715,
                    49,
                    714,
                    661,
                    694,
                    41,
                    521,
                    116,
                    695,
                    717,
                    158,
                    1,
                    335,
                    22,
                    610
                ]
            },
            {
                "id":14,
                "name":"Swords-Dance",
                "accuracy":null,
                "pp":20,
                "priority":0,
                "power":null,
                "damage_class":"status",
                "move_type":1,
                "pokemon":[
                    182,
                    212,
                    255,
                    211,
                    271,
                    273,
                    251,
                    254,
                    215,
                    291,
                    10065,
                    270,
                    252,
                    10040,
                    216,
                    257,
                    10050,
                    253,
                    275,
                    274,
                    217,
                    285,
                    10068,
                    272,
                    214,
                    689,
                    660,
                    28,
                    72,
                    693,
                    680,
                    662,
                    701,
                    674,
                    70,
                    663,
                    46,
                    44,
                    395,
                    357,
                    459,
                    342,
                    452,
                    187,
                    315,
                    10006,
                    188,
                    402,
                    207,
                    105,
                    3,
                    104,
                    123,
                    10057,
                    10024,
                    447,
                    192,
                    191,
                    10026,
                    189,
                    69,
                    359,
                    111,
                    227,
                    10046,
                    345,
                    73,
                    10078,
                    108,
                    10079,
                    504,
                    408,
                    503,
                    501,
                    497,
                    589,
                    502,
                    460,
                    588,
                    407,
                    493,
                    496,
                    392,
                    505,
                    451,
                    495,
                    455,
                    463,
                    420,
                    491,
                    445,
                    454,
                    409,
                    492,
                    406,
                    391,
                    586,
                    448,
                    10034,
                    102,
                    15,
                    10059,
                    545,
                    2,
                    10035,
                    98,
                    557,
                    6,
                    10060,
                    10047,
                    141,
                    10052,
                    558,
                    99,
                    465,
                    47,
                    472,
                    464,
                    303,
                    421,
                    470,
                    103,
                    475,
                    114,
                    71,
                    83,
                    256,
                    112,
                    20,
                    346,
                    27,
                    151,
                    461,
                    160,
                    661,
                    529,
                    10033,
                    331,
                    542,
                    152,
                    681,
                    10090,
                    332,
                    347,
                    530,
                    45,
                    10058,
                    158,
                    43,
                    10021,
                    5,
                    127,
                    165,
                    1,
                    335,
                    679,
                    286,
                    4,
                    166,
                    692,
                    652,
                    153,
                    159,
                    549,
                    154,
                    383,
                    619,
                    639,
                    571,
                    387,
                    626,
                    598,
                    638,
                    390,
                    611,
                    645,
                    688,
                    620,
                    570,
                    647,
                    640,
                    610,
                    624,
                    348,
                    388,
                    612,
                    389,
                    650,
                    625,
                    675,
                    341,
                    651,
                    384,
                    614
                ]
            }
        ]

### Information on one Move [GET /move/{move_id}]

+ Parameters
    + move_id (number) - ID of the move in the form of an integer

+ Response 200 (application/json)

        {
            "id":1,
            "name":"Pound",
            "accuracy":100,
            "pp":35,
            "priority":0,
            "power":40,
            "damage_class":"physical",
            "move_type":1,
            "pokemon":[
                174,
                173,
                242,
                254,
                10065,
                252,
                253,
                275,
                274,
                238,
                10069,
                657,
                656,
                440,
                124,
                97,
                96,
                192,
                393,
                457,
                428,
                316,
                576,
                574,
                427,
                572,
                456,
                575,
                594,
                89,
                295,
                113,
                317,
                293,
                151,
                294,
                531,
                694,
                534,
                35,
                532,
                533,
                39,
                88,
                10088,
                619,
                622,
                623,
                569,
                658,
                620,
                568
            ]
        }


## Type [/type/{?offset,limit}]

### List all types [GET]

+ Parameters
    + offset (integer, optional) - ID of the first Type to be returned
        + Default: 0
    + limit (integer, optional) - Number of Type to return
        + Default: 10

+ Response 200(application/json)

        [
            {
                "id":1,
                "name":"Normal",
                "generation":1,
                "double_damage_to":[
        
                ],
                "double_damage_from":[
                    2
                ],
                "half_damage_to":[
                    6,
                    9
                ],
                "half_damage_from":[
        
                ],
                "no_damage_to":[
                    8
                ],
                "no_damage_from":[
                    8
                ],
                "moves":[
                    1,
                    3,
                    4,
                    5,
                    6,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    18,
                    20,
                    21,
                    23,
                    25,
                    29,
                    30,
                    31,
                    32,
                    33,
                    34,
                    35,
                    36,
                    37,
                    38,
                    39,
                    43,
                    45,
                    46,
                    47,
                    48,
                    49,
                    50,
                    63,
                    70,
                    74,
                    98,
                    99,
                    102,
                    103,
                    104,
                    105,
                    106,
                    107,
                    108,
                    111,
                    116,
                    117,
                    118,
                    120,
                    121,
                    129,
                    130,
                    131,
                    132,
                    135,
                    137,
                    140,
                    142,
                    144,
                    146,
                    148,
                    150,
                    153,
                    154,
                    158,
                    159,
                    160,
                    161,
                    162,
                    163,
                    164,
                    165,
                    166,
                    170,
                    173,
                    175,
                    176,
                    182,
                    184,
                    187,
                    193,
                    195,
                    199,
                    203,
                    206,
                    207,
                    208,
                    212,
                    213,
                    214,
                    215,
                    216,
                    217,
                    218,
                    219,
                    220,
                    226,
                    227,
                    229,
                    230,
                    234,
                    237,
                    244,
                    245,
                    252,
                    253,
                    254,
                    255,
                    256,
                    263,
                    265,
                    266,
                    267,
                    270,
                    273,
                    274,
                    278,
                    281,
                    283,
                    287,
                    290,
                    293,
                    298,
                    303,
                    304,
                    306,
                    311,
                    316,
                    321,
                    335,
                    336,
                    343,
                    363,
                    364,
                    367,
                    376,
                    378,
                    381,
                    382,
                    383,
                    387,
                    416,
                    431,
                    445,
                    449,
                    458,
                    462,
                    493,
                    494,
                    495,
                    496,
                    497,
                    498,
                    504,
                    513,
                    514,
                    516,
                    526,
                    541,
                    543,
                    546,
                    547,
                    568,
                    586,
                    589,
                    590,
                    603,
                    606,
                    607,
                    610
                ],
                "num_primary_type":98,
                "num_secondary_type":4
            },
            {
                "id":2,
                "name":"Fighting",
                "generation":1,
                "double_damage_to":[
                    1,
                    6,
                    9,
                    15,
                    17
                ],
                "double_damage_from":[
                    3,
                    14,
                    18
                ],
                "half_damage_to":[
                    3,
                    4,
                    7,
                    14,
                    18
                ],
                "half_damage_from":[
                    6,
                    7,
                    17
                ],
                "no_damage_to":[
                    8
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    2,
                    24,
                    26,
                    27,
                    66,
                    67,
                    68,
                    69,
                    136,
                    167,
                    179,
                    183,
                    197,
                    223,
                    233,
                    238,
                    249,
                    264,
                    276,
                    279,
                    280,
                    292,
                    327,
                    339,
                    358,
                    359,
                    370,
                    395,
                    396,
                    409,
                    410,
                    411,
                    480,
                    490,
                    501,
                    509,
                    515,
                    533,
                    548,
                    560,
                    561,
                    612
                ],
                "num_primary_type":27,
                "num_secondary_type":26
            },
            {
                "id":3,
                "name":"Flying",
                "generation":1,
                "double_damage_to":[
                    2,
                    7,
                    12
                ],
                "double_damage_from":[
                    6,
                    13,
                    15
                ],
                "half_damage_to":[
                    6,
                    9,
                    13
                ],
                "half_damage_from":[
                    2,
                    7,
                    12
                ],
                "no_damage_to":[
        
                ],
                "no_damage_from":[
                    5
                ],
                "moves":[
                    16,
                    17,
                    19,
                    64,
                    65,
                    119,
                    143,
                    177,
                    297,
                    314,
                    332,
                    340,
                    355,
                    365,
                    366,
                    403,
                    413,
                    432,
                    448,
                    507,
                    512,
                    542,
                    613,
                    620
                ],
                "num_primary_type":4,
                "num_secondary_type":97
            },
            {
                "id":4,
                "name":"Poison",
                "generation":1,
                "double_damage_to":[
                    12,
                    18
                ],
                "double_damage_from":[
                    5,
                    14
                ],
                "half_damage_to":[
                    4,
                    5,
                    6,
                    8
                ],
                "half_damage_from":[
                    2,
                    4,
                    7,
                    12,
                    18
                ],
                "no_damage_to":[
                    9
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    40,
                    51,
                    77,
                    92,
                    123,
                    124,
                    139,
                    151,
                    188,
                    305,
                    342,
                    380,
                    390,
                    398,
                    440,
                    441,
                    474,
                    482,
                    489,
                    491,
                    499,
                    562,
                    599
                ],
                "num_primary_type":28,
                "num_secondary_type":34
            },
            {
                "id":5,
                "name":"Ground",
                "generation":1,
                "double_damage_to":[
                    4,
                    6,
                    9,
                    10,
                    13
                ],
                "double_damage_from":[
                    11,
                    12,
                    15
                ],
                "half_damage_to":[
                    7,
                    12
                ],
                "half_damage_from":[
                    4,
                    6
                ],
                "no_damage_to":[
                    3
                ],
                "no_damage_from":[
                    13
                ],
                "moves":[
                    28,
                    89,
                    90,
                    91,
                    125,
                    155,
                    189,
                    191,
                    198,
                    222,
                    300,
                    328,
                    341,
                    414,
                    426,
                    523,
                    529,
                    563,
                    614,
                    615,
                    616,
                    619
                ],
                "num_primary_type":32,
                "num_secondary_type":35
            },
            {
                "id":6,
                "name":"Rock",
                "generation":1,
                "double_damage_to":[
                    3,
                    7,
                    10,
                    15
                ],
                "double_damage_from":[
                    2,
                    5,
                    9,
                    11,
                    12
                ],
                "half_damage_to":[
                    2,
                    5,
                    9
                ],
                "half_damage_from":[
                    1,
                    3,
                    4,
                    10
                ],
                "no_damage_to":[
        
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    88,
                    157,
                    201,
                    205,
                    246,
                    317,
                    350,
                    397,
                    408,
                    439,
                    444,
                    446,
                    457,
                    469,
                    479,
                    591
                ],
                "num_primary_type":44,
                "num_secondary_type":14
            },
            {
                "id":7,
                "name":"Bug",
                "generation":1,
                "double_damage_to":[
                    12,
                    14,
                    17
                ],
                "double_damage_from":[
                    3,
                    6,
                    10
                ],
                "half_damage_to":[
                    2,
                    3,
                    4,
                    8,
                    9,
                    10,
                    18
                ],
                "half_damage_from":[
                    2,
                    5,
                    12
                ],
                "no_damage_to":[
        
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    41,
                    42,
                    81,
                    141,
                    169,
                    210,
                    224,
                    294,
                    318,
                    324,
                    369,
                    404,
                    405,
                    450,
                    454,
                    455,
                    456,
                    476,
                    483,
                    522,
                    537,
                    564,
                    565,
                    600,
                    611
                ],
                "num_primary_type":69,
                "num_secondary_type":3
            },
            {
                "id":8,
                "name":"Ghost",
                "generation":1,
                "double_damage_to":[
                    8,
                    14
                ],
                "double_damage_from":[
                    8,
                    17
                ],
                "half_damage_to":[
                    17
                ],
                "half_damage_from":[
                    4,
                    7
                ],
                "no_damage_to":[
                    1
                ],
                "no_damage_from":[
                    1,
                    2
                ],
                "moves":[
                    101,
                    109,
                    122,
                    171,
                    174,
                    180,
                    194,
                    247,
                    288,
                    310,
                    325,
                    421,
                    425,
                    466,
                    467,
                    506,
                    566,
                    567
                ],
                "num_primary_type":32,
                "num_secondary_type":14
            },
            {
                "id":9,
                "name":"Steel",
                "generation":2,
                "double_damage_to":[
                    6,
                    15,
                    18
                ],
                "double_damage_from":[
                    2,
                    5,
                    10
                ],
                "half_damage_to":[
                    9,
                    10,
                    11,
                    13
                ],
                "half_damage_from":[
                    1,
                    3,
                    6,
                    7,
                    9,
                    12,
                    14,
                    15,
                    16,
                    18
                ],
                "no_damage_to":[
        
                ],
                "no_damage_from":[
                    4
                ],
                "moves":[
                    211,
                    231,
                    232,
                    309,
                    319,
                    334,
                    353,
                    360,
                    368,
                    418,
                    429,
                    430,
                    442,
                    443,
                    475,
                    484,
                    508,
                    544,
                    588
                ],
                "num_primary_type":27,
                "num_secondary_type":22
            },
            {
                "id":10,
                "name":"Fire",
                "generation":1,
                "double_damage_to":[
                    7,
                    9,
                    12,
                    15
                ],
                "double_damage_from":[
                    5,
                    6,
                    11
                ],
                "half_damage_to":[
                    6,
                    10,
                    11,
                    16
                ],
                "half_damage_from":[
                    7,
                    9,
                    10,
                    12,
                    15,
                    18
                ],
                "no_damage_to":[
        
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    7,
                    52,
                    53,
                    83,
                    126,
                    172,
                    221,
                    241,
                    257,
                    261,
                    284,
                    299,
                    307,
                    315,
                    394,
                    424,
                    436,
                    463,
                    481,
                    488,
                    510,
                    517,
                    519,
                    535,
                    545,
                    551,
                    552,
                    557,
                    558,
                    595
                ],
                "num_primary_type":53,
                "num_secondary_type":12
            },
            {
                "id":11,
                "name":"Water",
                "generation":1,
                "double_damage_to":[
                    5,
                    6,
                    10
                ],
                "double_damage_from":[
                    12,
                    13
                ],
                "half_damage_to":[
                    11,
                    12,
                    16
                ],
                "half_damage_from":[
                    9,
                    10,
                    11,
                    15
                ],
                "no_damage_to":[
        
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    55,
                    56,
                    57,
                    61,
                    110,
                    127,
                    128,
                    145,
                    152,
                    190,
                    240,
                    250,
                    291,
                    308,
                    323,
                    330,
                    346,
                    352,
                    362,
                    392,
                    401,
                    453,
                    487,
                    503,
                    518,
                    534,
                    592,
                    594,
                    618
                ],
                "num_primary_type":114,
                "num_secondary_type":14
            },
            {
                "id":12,
                "name":"Grass",
                "generation":1,
                "double_damage_to":[
                    5,
                    6,
                    11
                ],
                "double_damage_from":[
                    3,
                    4,
                    7,
                    10,
                    15
                ],
                "half_damage_to":[
                    3,
                    4,
                    7,
                    9,
                    10,
                    12,
                    16
                ],
                "half_damage_from":[
                    5,
                    11,
                    12,
                    13
                ],
                "no_damage_to":[
        
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    22,
                    71,
                    72,
                    73,
                    75,
                    76,
                    78,
                    79,
                    80,
                    147,
                    178,
                    202,
                    235,
                    275,
                    302,
                    312,
                    320,
                    331,
                    338,
                    345,
                    348,
                    388,
                    402,
                    412,
                    437,
                    438,
                    447,
                    452,
                    465,
                    520,
                    532,
                    536,
                    538,
                    571,
                    572,
                    580,
                    596
                ],
                "num_primary_type":70,
                "num_secondary_type":25
            },
            {
                "id":13,
                "name":"Electric",
                "generation":1,
                "double_damage_to":[
                    3,
                    11
                ],
                "double_damage_from":[
                    5
                ],
                "half_damage_to":[
                    12,
                    13,
                    16
                ],
                "half_damage_from":[
                    3,
                    9,
                    13
                ],
                "no_damage_to":[
                    5
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    9,
                    84,
                    85,
                    86,
                    87,
                    192,
                    209,
                    268,
                    344,
                    351,
                    393,
                    422,
                    435,
                    451,
                    486,
                    521,
                    527,
                    528,
                    550,
                    559,
                    569,
                    570,
                    582,
                    598,
                    602,
                    604,
                    609
                ],
                "num_primary_type":50,
                "num_secondary_type":6
            },
            {
                "id":14,
                "name":"Psychic",
                "generation":1,
                "double_damage_to":[
                    2,
                    4
                ],
                "double_damage_from":[
                    7,
                    8,
                    17
                ],
                "half_damage_to":[
                    9,
                    14
                ],
                "half_damage_from":[
                    2,
                    14
                ],
                "no_damage_to":[
                    17
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    60,
                    93,
                    94,
                    95,
                    96,
                    97,
                    100,
                    112,
                    113,
                    115,
                    133,
                    134,
                    138,
                    149,
                    156,
                    243,
                    248,
                    271,
                    272,
                    277,
                    285,
                    286,
                    295,
                    296,
                    322,
                    326,
                    347,
                    354,
                    356,
                    357,
                    361,
                    375,
                    377,
                    379,
                    384,
                    385,
                    391,
                    427,
                    428,
                    433,
                    461,
                    470,
                    471,
                    472,
                    473,
                    477,
                    478,
                    485,
                    500,
                    502,
                    505,
                    531,
                    540,
                    593
                ],
                "num_primary_type":57,
                "num_secondary_type":33
            },
            {
                "id":15,
                "name":"Ice",
                "generation":1,
                "double_damage_to":[
                    3,
                    5,
                    12,
                    16
                ],
                "double_damage_from":[
                    2,
                    6,
                    9,
                    10
                ],
                "half_damage_to":[
                    9,
                    10,
                    11,
                    15
                ],
                "half_damage_from":[
                    15
                ],
                "no_damage_to":[
        
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    8,
                    54,
                    58,
                    59,
                    62,
                    114,
                    181,
                    196,
                    258,
                    301,
                    329,
                    333,
                    419,
                    420,
                    423,
                    524,
                    549,
                    553,
                    554,
                    556,
                    573
                ],
                "num_primary_type":25,
                "num_secondary_type":14
            },
            {
                "id":16,
                "name":"Dragon",
                "generation":1,
                "double_damage_to":[
                    16
                ],
                "double_damage_from":[
                    15,
                    16,
                    18
                ],
                "half_damage_to":[
                    9
                ],
                "half_damage_from":[
                    10,
                    11,
                    12,
                    13
                ],
                "no_damage_to":[
                    18
                ],
                "no_damage_from":[
        
                ],
                "moves":[
                    82,
                    200,
                    225,
                    239,
                    337,
                    349,
                    406,
                    407,
                    434,
                    459,
                    460,
                    525,
                    530
                ],
                "num_primary_type":32,
                "num_secondary_type":18
            },
            {
                "id":17,
                "name":"Dark",
                "generation":2,
                "double_damage_to":[
                    8,
                    14
                ],
                "double_damage_from":[
                    2,
                    7,
                    18
                ],
                "half_damage_to":[
                    2,
                    17,
                    18
                ],
                "half_damage_from":[
                    8,
                    17
                ],
                "no_damage_to":[
        
                ],
                "no_damage_from":[
                    14
                ],
                "moves":[
                    44,
                    168,
                    185,
                    228,
                    242,
                    251,
                    259,
                    260,
                    262,
                    269,
                    282,
                    289,
                    313,
                    371,
                    372,
                    373,
                    374,
                    386,
                    389,
                    399,
                    400,
                    415,
                    417,
                    464,
                    468,
                    492,
                    511,
                    539,
                    555,
                    575,
                    576,
                    621
                ],
                "num_primary_type":31,
                "num_secondary_type":20
            },
            {
                "id":18,
                "name":"Fairy",
                "generation":6,
                "double_damage_to":[
                    2,
                    16,
                    17
                ],
                "double_damage_from":[
                    4,
                    9
                ],
                "half_damage_to":[
                    4,
                    9,
                    10
                ],
                "half_damage_from":[
                    2,
                    7,
                    17
                ],
                "no_damage_to":[
        
                ],
                "no_damage_from":[
                    16
                ],
                "moves":[
                    186,
                    204,
                    236,
                    574,
                    577,
                    578,
                    579,
                    581,
                    583,
                    584,
                    585,
                    587,
                    597,
                    601,
                    605,
                    608,
                    617
                ],
                "num_primary_type":18,
                "num_secondary_type":23
            }
        ]

### Information on one type [GET /type/{type_id}]

+ Parameters
    + type_id (number) - ID of the type in the form of an integer

+ Response 200(application/json)

        {
            "id":1,
            "name":"Normal",
            "generation":1,
            "double_damage_to":[
        
            ],
            "double_damage_from":[
                2
            ],
            "half_damage_to":[
                6,
                9
            ],
            "half_damage_from":[
        
            ],
            "no_damage_to":[
                8
            ],
            "no_damage_from":[
                8
            ],
            "moves":[
                1,
                3,
                4,
                5,
                6,
                10,
                11,
                12,
                13,
                14,
                15,
                18,
                20,
                21,
                23,
                25,
                29,
                30,
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                43,
                45,
                46,
                47,
                48,
                49,
                50,
                63,
                70,
                74,
                98,
                99,
                102,
                103,
                104,
                105,
                106,
                107,
                108,
                111,
                116,
                117,
                118,
                120,
                121,
                129,
                130,
                131,
                132,
                135,
                137,
                140,
                142,
                144,
                146,
                148,
                150,
                153,
                154,
                158,
                159,
                160,
                161,
                162,
                163,
                164,
                165,
                166,
                170,
                173,
                175,
                176,
                182,
                184,
                187,
                193,
                195,
                199,
                203,
                206,
                207,
                208,
                212,
                213,
                214,
                215,
                216,
                217,
                218,
                219,
                220,
                226,
                227,
                229,
                230,
                234,
                237,
                244,
                245,
                252,
                253,
                254,
                255,
                256,
                263,
                265,
                266,
                267,
                270,
                273,
                274,
                278,
                281,
                283,
                287,
                290,
                293,
                298,
                303,
                304,
                306,
                311,
                316,
                321,
                335,
                336,
                343,
                363,
                364,
                367,
                376,
                378,
                381,
                382,
                383,
                387,
                416,
                431,
                445,
                449,
                458,
                462,
                493,
                494,
                495,
                496,
                497,
                498,
                504,
                513,
                514,
                516,
                526,
                541,
                543,
                546,
                547,
                568,
                586,
                589,
                590,
                603,
                606,
                607,
                610
            ],
            "num_primary_type":98,
            "num_secondary_type":4
        }