version: "2"

# A Docker Compose file for configuration of the production environment

services:
  lb:
    extends:
      file: docker-compose-common.yml
      service: lb
    image: sthakkar14/swecune_lb
    environment:
      # Always deploy to n1 so the lb always has the same IP address. This is
      # just for convenience and isn't strictly necessary.
      - "constraint:node==*n1"

  app:
    extends:
      file: docker-compose-common.yml
      service: app
    image: sthakkar14/swecune_app
    expose:
      # Expose port 8000 so it's only visibile on the container, not the host
      - "8000"
    env_file: swecluster/docker.env
    command: gunicorn server:app --bind 0.0.0.0:8000
      # Run Gunicorn to serve app requests

  data:
    extends:
      file: docker-compose-common.yml
      service: data

networks:
  backend: {}
